name: CSYTOpen
version: '${project.version}'
main: fun.csyt.open.CSYTOpen
api-version: '1.19'
depend:
  - UhcCore
commands:
  discord:
    permission: minecraft.op
    aliases:
      - dsc
      - dbc
    permission-message: Nu-uh!
#  assign: