name: TurfWars
version: '${project.version}'
main: fun.csyt.turfwars.TurfWars
api-version: '1.19'
depend:
  - WorldEdit
softdepend:
  - Multiverse-Core
  - TAB
loadbefore:
  - Construction
  - CP
  - countdown
commands:
  turfmanager:
    permission: minecraft.op
  turf:
    permission: minecraft.op