loc:
  1:
    x: -8
    y: 86
    z: -55
  2:
    x: -2
    y: 86
    z: -55
  3:
    x: 6
    y: 86
    z: -55
  4:
    x: 12
    y: 86
    z: -55
schematic:
  prefix: "./plugins/FastAsyncWorldEdit/schematics/north/"
  suffix: ".schem"