# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
    - run: |
        rm ChunkLockPrototype/target/original-*.jar
        rm CommandPortalClient/target/original-*.jar
        rm CommandPortalServer/target/original-*.jar
        rm Construction/target/original-*.jar
        rm MusicManager/target/original-*.jar
        rm PatternSaver/target/original-*.jar
        rm countdown/target/original-*.jar
        rm AnimationClient/target/original-*.jar
        rm CapturePoint/target/original-*.jar
    - uses: actions/upload-artifact@v3
      with:
        name: plugins
        path: |
          ChunkLockPrototype/target/*.jar
          CommandPortalClient/target/*.jar
          CommandPortalServer/target/*.jar
          Construction/target/*.jar
          MusicManager/target/*.jar
          PatternSaver/target/*.jar
          PointEvaluator/target/*.jar
          countdown/target/*.jar
          CapturePoint/target/*.jar
          AnimationClient/target/*.jar
          index.json
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ChunkLockPrototype/target/*.jar
          CommandPortalClient/target/*.jar
          CommandPortalServer/target/*.jar
          Construction/target/*.jar
          MusicManager/target/*.jar
          PatternSaver/target/*.jar
          PointEvaluator/target/*.jar
          countdown/target/*.jar
          CapturePoint/target/*.jar
          AnimationClient/target/*.jar
          index.json
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3