# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
      - run: echo "NOW=$${{ steps.version.outputs.builddate }}" | sed 's/:/./g' >> $GITHUB_ENV
      # Set the date time
      - name: Retrieve current Date Time in Singapore TimeZone
        shell: bash
        run: echo "START_TIME=$(TZ=":Europe/Prague" date -R|sed 's/.....$//')" >> $GITHUB_ENV
      # Fetch the date time as Github ENV variable
      - name: print date
        run: echo ${{ env.START_TIME }}
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package --settings=./.mvn/settings.xml -Drevision=$NOW
      - run: |
          rm ChunkLockPrototype/target/original-*.jar
          rm Construction/target/original-*.jar
          rm MusicManager/target/original-*.jar
          rm PatternSaver/target/original-*.jar
          rm countdown/target/original-*.jar
          rm CapturePoint/target/original-*.jar
          rm DecisionDomeDecider/target/original-*.jar
          rm AcceptDiscordBot/target/original-*.jar
          rm CSYTools/target/original-*.jar
          rm DataPackToolBox/target/original-*.jar
          rm backup/target/original-*.jar
          rm TurfWars/target/original-*.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build, created at ${{ github.event.repository.updated_at}}"
          files: |
            ChunkLockPrototype/target/*.jar
            Construction/target/*.jar
            MusicManager/target/*.jar
            PatternSaver/target/*.jar
            PointEvaluator/target/*.jar
            countdown/target/*.jar
            CapturePoint/target/*.jar
            AcceptDiscordBot/target/*.jar
            DecisionDomeDecider/target/*.jar
            CSYTools/target/*.jar
            DataPackToolBox/target/*.jar
            backup/target/*.jar
            TurfWars/target/*.jar
            index.json
