# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

  cache:
    name: Cache
    runs-on: ubuntu-latest
    steps:
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

  codeqlinit:
    name: CodeQL init
    runs-on: ubuntu-latest
    needs: checkout
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

  javasetup:
    name: Java Setup
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ codeqlinit,javasetup,cache ]
    steps:
    - name: Build with Maven
      run: mvn package --file pom.xml
    - run: |
        rm ChunkLockPrototype/target/original-*.jar
        rm CommandPortalClient/target/original-*.jar
        rm CommandPortalServer/target/original-*.jar
        rm Construction/target/original-*.jar
        rm MusicManager/target/original-*.jar
        rm PatternSaver/target/original-*.jar
        rm PointEvaluator/target/original-*.jar
        rm countdown/target/original-*.jar

  artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/upload-artifact@v3
      with:
        name: plugins
        path: |
          ChunkLockPrototype/target/*.jar
          CommandPortalClient/target/*.jar
          CommandPortalServer/target/*.jar
          Construction/target/*.jar
          MusicManager/target/*.jar
          PatternSaver/target/*.jar
          PointEvaluator/target/*.jar
          countdown/target/*.jar
          index.json
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ChunkLockPrototype/target/*.jar
          CommandPortalClient/target/*.jar
          CommandPortalServer/target/*.jar
          Construction/target/*.jar
          MusicManager/target/*.jar
          PatternSaver/target/*.jar
          PointEvaluator/target/*.jar
          countdown/target/*.jar
          index.json
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
  graph:
    name: Dependecy graph
    runs-on: ubuntu-latest
    needs: codeql
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3